export type SqlMigration = {
  id: string;
  sql: string;
};

export const SQL_MIGRATIONS: SqlMigration[] = [
  {
    id: '001_raw_sql_core_schema',
    sql: `
      BEGIN
        -- Create USERS table
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE TABLE USERS (
              ID VARCHAR2(36) PRIMARY KEY,
              EMAIL VARCHAR2(4000) NOT NULL UNIQUE,
              PASSWORD VARCHAR2(4000) NOT NULL,
              USER_NAME VARCHAR2(4000) NOT NULL,
              COUNTRY VARCHAR2(2) NOT NULL,
              CURRENCY VARCHAR2(3) NOT NULL,
              STRIPE_CUSTOMER_ID VARCHAR2(4000) UNIQUE,
              DEFAULT_PAYMENT_METHOD_ID VARCHAR2(4000),
              MONTHLY_MANAGEMENT_FEE NUMBER(12, 0),
              ACCOUNT_VALUE NUMBER(18, 2),
              CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
              UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
          ';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create USERS_STRIPE_CUSTOMER_ID_IDX index
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX USERS_STRIPE_CUSTOMER_ID_IDX ON USERS (STRIPE_CUSTOMER_ID)';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create STRIPE_PAYMENT_METHODS table
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE TABLE STRIPE_PAYMENT_METHODS (
              ID VARCHAR2(36) PRIMARY KEY,
              USER_ID VARCHAR2(36) NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
              STRIPE_PAYMENT_METHOD_ID VARCHAR2(4000) NOT NULL UNIQUE,
              METHOD_TYPE VARCHAR2(4000) NOT NULL,
              IS_DEFAULT NUMBER(1) DEFAULT 0 NOT NULL,
              LAST4 VARCHAR2(4),
              BRAND VARCHAR2(4000),
              EXPIRY_MONTH NUMBER(10),
              EXPIRY_YEAR NUMBER(10),
              METADATA CLOB,
              CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
              UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
          ';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create STRIPE_PM_USER_ID_IDX index
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX STRIPE_PM_USER_ID_IDX ON STRIPE_PAYMENT_METHODS (USER_ID)';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create STRIPE_PAYMENTS table
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE TABLE STRIPE_PAYMENTS (
              ID VARCHAR2(36) PRIMARY KEY,
              USER_ID VARCHAR2(36) NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
              STRIPE_PAYMENT_INTENT_ID VARCHAR2(4000) UNIQUE,
              STRIPE_CHECKOUT_SESSION_ID VARCHAR2(4000) UNIQUE,
              AMOUNT_GBP NUMBER(10) NOT NULL,
              AMOUNT_USER_CURRENCY NUMBER(10),
              USER_CURRENCY VARCHAR2(3),
              FX_QUOTE_ID VARCHAR2(4000),
              STATUS VARCHAR2(4000) DEFAULT ''pending'' NOT NULL,
              PAYMENT_METHOD_ID VARCHAR2(4000),
              IDEMPOTENCY_KEY VARCHAR2(4000) NOT NULL UNIQUE,
              METADATA CLOB,
              CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
              UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
          ';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create STRIPE_PAYMENTS_USER_ID_IDX index
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX STRIPE_PAYMENTS_USER_ID_IDX ON STRIPE_PAYMENTS (USER_ID)';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create STRIPE_USAGE_CHARGES table
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE TABLE STRIPE_USAGE_CHARGES (
              ID VARCHAR2(36) PRIMARY KEY,
              USER_ID VARCHAR2(36) NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
              STRIPE_INVOICE_ID VARCHAR2(4000),
              STRIPE_SUBSCRIPTION_ID VARCHAR2(4000),
              STRIPE_SUBSCRIPTION_ITEM_ID VARCHAR2(4000),
              STRIPE_PAYMENT_INTENT_ID VARCHAR2(4000),
              AMOUNT_GBP NUMBER(10) NOT NULL,
              DESCRIPTION VARCHAR2(4000),
              BILLING_PERIOD_START DATE NOT NULL,
              BILLING_PERIOD_END DATE NOT NULL,
              STATUS VARCHAR2(4000) DEFAULT ''pending'' NOT NULL,
              IDEMPOTENCY_KEY VARCHAR2(4000) NOT NULL UNIQUE,
              USAGE_REPORTED_AT TIMESTAMP WITH TIME ZONE,
              CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
              UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
          ';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create STRIPE_UC_USER_ID_IDX index
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX STRIPE_UC_USER_ID_IDX ON STRIPE_USAGE_CHARGES (USER_ID)';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create STRIPE_UC_PERIOD_IDX index
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX STRIPE_UC_PERIOD_IDX ON STRIPE_USAGE_CHARGES (BILLING_PERIOD_START, BILLING_PERIOD_END)';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Add STRIPE_SUBSCRIPTION_ID column if not exists
        DECLARE
          v_count NUMBER;
        BEGIN
          SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
          WHERE TABLE_NAME = 'STRIPE_USAGE_CHARGES' AND COLUMN_NAME = 'STRIPE_SUBSCRIPTION_ID';
          IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE STRIPE_USAGE_CHARGES ADD STRIPE_SUBSCRIPTION_ID VARCHAR2(4000)';
          END IF;
        END;

        -- Add STRIPE_SUBSCRIPTION_ITEM_ID column if not exists
        DECLARE
          v_count NUMBER;
        BEGIN
          SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
          WHERE TABLE_NAME = 'STRIPE_USAGE_CHARGES' AND COLUMN_NAME = 'STRIPE_SUBSCRIPTION_ITEM_ID';
          IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE STRIPE_USAGE_CHARGES ADD STRIPE_SUBSCRIPTION_ITEM_ID VARCHAR2(4000)';
          END IF;
        END;

        -- Add STRIPE_INVOICE_ID column if not exists
        DECLARE
          v_count NUMBER;
        BEGIN
          SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
          WHERE TABLE_NAME = 'STRIPE_USAGE_CHARGES' AND COLUMN_NAME = 'STRIPE_INVOICE_ID';
          IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE STRIPE_USAGE_CHARGES ADD STRIPE_INVOICE_ID VARCHAR2(4000)';
          END IF;
        END;

        -- Add USAGE_REPORTED_AT column if not exists
        DECLARE
          v_count NUMBER;
        BEGIN
          SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
          WHERE TABLE_NAME = 'STRIPE_USAGE_CHARGES' AND COLUMN_NAME = 'USAGE_REPORTED_AT';
          IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE STRIPE_USAGE_CHARGES ADD USAGE_REPORTED_AT TIMESTAMP WITH TIME ZONE';
          END IF;
        END;

        -- Create STRIPE_UC_SUBSCRIPTION_IDX index (after columns guaranteed to exist)
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX STRIPE_UC_SUBSCRIPTION_IDX ON STRIPE_USAGE_CHARGES (STRIPE_SUBSCRIPTION_ID, STRIPE_SUBSCRIPTION_ITEM_ID)';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create STRIPE_BILLING_SUBSCRIPTIONS table
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE TABLE STRIPE_BILLING_SUBSCRIPTIONS (
              ID VARCHAR2(36) PRIMARY KEY,
              USER_ID VARCHAR2(36) NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
              STRIPE_SUBSCRIPTION_ID VARCHAR2(4000) NOT NULL UNIQUE,
              STRIPE_SUBSCRIPTION_ITEM_ID VARCHAR2(4000) NOT NULL,
              STRIPE_PRICE_ID VARCHAR2(4000) NOT NULL,
              STATUS VARCHAR2(4000) DEFAULT ''incomplete'' NOT NULL,
              CURRENT_PERIOD_START DATE,
              CURRENT_PERIOD_END DATE,
              CANCEL_AT_PERIOD_END NUMBER(1) DEFAULT 0 NOT NULL,
              CANCELED_AT TIMESTAMP WITH TIME ZONE,
              CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
              UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
          ';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;

        -- Create STRIPE_BS_USER_ID_IDX index
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX STRIPE_BS_USER_ID_IDX ON STRIPE_BILLING_SUBSCRIPTIONS (USER_ID)';
        EXCEPTION
          WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;
      END;
    `,
  },
  {
    id: '002_add_email_sent_at_to_usage_charges',
    sql: `
      DECLARE
        v_count NUMBER;
      BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
        WHERE TABLE_NAME = 'STRIPE_USAGE_CHARGES' AND COLUMN_NAME = 'EMAIL_SENT_AT';
        IF v_count = 0 THEN
          EXECUTE IMMEDIATE 'ALTER TABLE STRIPE_USAGE_CHARGES ADD EMAIL_SENT_AT TIMESTAMP WITH TIME ZONE';
        END IF;
      END;
    `,
  },
];
